blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/chrisreddington/flight-school/blob/main/README.md
    about: Check out the documentation for guides and examples
